
def historia(parnome):
    print('O ano era 1460. O vilarejo de Rothenburg estava sendo atacado por bárbaros de um vilarejo próximo: Melchior')
    print('Milo Grannus, o rei de Rothenburg, foi acusado de fraude pelo próprio irmão, Roland, o rei de Melchior.  ')
    print('Milo Grannus: Caso você faça mal a alguém do meu vilarejo, declararei guerra eterna entre Rothenburg e Melchior.')
    print('Roland: Isso se você estiver vivo até lá.')
    print('Roland dá um sorriso malvado e levanta sua espada enquanto seus capangas seguram seu irmão no chão. De repente, se escuta um barulho vindo atrás da porta.')
    print('Roland: Quem está ai?')
    print('Silêncio.')
    print('Roland: QUEM ESTÁ AI?')
    print(f'Milo Grannus: {parnome} ,filho, fique ai... ')
    print('Roland deu mais um sorriso. Dessa vez, ele estava genuinamente feliz.')
    print('Roland: Vou finalmente poder me vingar de todas as coisas que você fez para mim, Milo...')
    print('Em questões de segundos, Milo conseguiu lutar com o irmão. Quando estava prestes a perder a luta, Milo gritou...')
    print(f'{parnome}, corre!')
    print(f'Com lágrimas nos olhos, e mesmo com o receio de deixar seu pai para trás, {parnome} correu. Quando estava prestes a chegar nos portões do castelo, você ouviu um grito. Era de seu pai.')
    print('Ele pensou em dar meia volta e retonar para salvar seu pai, mas estaria arriscando sua própria vida.')
    print(f'Nesse dia, {parnome} jurou vingança. Pelo seu pai. Pelo povo de Rothenburg...')
    print('MELCHIOR.')
